SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tracks](
	[Track] [int] NOT NULL,
	[Year] [int] NULL,
	[StartCar] [int] NULL,
	[EndCar] [int] NULL,
	[CarPerHeat] [int] NULL,
	[HeatCount] [int] NULL,
 CONSTRAINT [U_Tracks] UNIQUE NONCLUSTERED 
(
	[Track] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


