USE [master]
GO

/* A script to create the SCOUTS database */

CREATE DATABASE [SCOUT_TRUCKS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SCOUT_TRUCKS_DATA', FILENAME = N'SCOUT_TRUCKS_data.mdf' , SIZE = 8192KB , MAXSIZE = 20480KB , FILEGROWTH = 0)
 LOG ON 
( NAME = N'SCOUT_TRUCKS_LOG', FILENAME = N'SCOUT_TRUCKS_log.mdf' , SIZE = 4096KB , MAXSIZE = 12288KB , FILEGROWTH = 0)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SCOUT_TRUCKS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SCOUT_TRUCKS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET ARITHABORT OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET  MULTI_USER 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SCOUT_TRUCKS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SCOUT_TRUCKS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SCOUT_TRUCKS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SCOUT_TRUCKS] SET  READ_WRITE 
GO


