USE [master]
GO

/* A script to create the CUBS database */

CREATE DATABASE [KUBKARS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KUBKARS_DATA', FILENAME = N'kubkars_data.mdf' , SIZE = 8192KB , MAXSIZE = 20480KB , FILEGROWTH = 0)
 LOG ON 
( NAME = N'KUBKARS_LOG', FILENAME = N'kubkars_log.mdf' , SIZE = 4096KB , MAXSIZE = 12288KB , FILEGROWTH = 0)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KUBKARS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KUBKARS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KUBKARS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KUBKARS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KUBKARS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KUBKARS] SET ARITHABORT OFF 
GO

ALTER DATABASE [KUBKARS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [KUBKARS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KUBKARS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KUBKARS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KUBKARS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KUBKARS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KUBKARS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KUBKARS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KUBKARS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KUBKARS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KUBKARS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KUBKARS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KUBKARS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KUBKARS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KUBKARS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KUBKARS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KUBKARS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KUBKARS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [KUBKARS] SET  MULTI_USER 
GO

ALTER DATABASE [KUBKARS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KUBKARS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KUBKARS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KUBKARS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [KUBKARS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [KUBKARS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [KUBKARS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [KUBKARS] SET  READ_WRITE 
GO


